apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: mongodb-veyz
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: mongodb-veyz
    app.kubernetes.io/part-of: mongo
  name: mongodb-veyz
  namespace: sde-rcook-tenant
spec:
  port:
    targetPort: 8080
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: mongodb-veyz
    weight: 100
status: {}
